import LocalizedStrings from 'react-native-localization';

let Strings = new LocalizedStrings({
    en: {
        Dir: "ltr",
        MY_APP: "My app",
        SHOP: "Shop",
        CATEGORIES: "Categories",
        HOME: "Home",
        SETTINGS: "Settings",
        LANGUAGE: "Language",
        EN: "English",
        FA: "Persian",
        FR: "French",
        RU: "Russian",
        WELCOME_STRING: "ٌWelcome to our shopping app",
        Enter_to_app: "Enter to app",
        UserName: "Email or Phone Number",
        Password: "Password",
        ForgetPassword: "Forget your password?",
        Make_New_Account: "Make new account",
        Terms: "By entering or registering in the program, you accept the terms and conditions of using the application services and its privacy rules",
        REGIONAL: "Regional",
        DarkMode: "Dark Mode",
    },
    ru: {
        Dir: "ltr",
        MY_APP: "Мое приложение",
        SHOP: "Магазин",
        CATEGORIES: "Категории",
        HOME: "Главная",
        SETTINGS: "Настройки",
        LANGUAGE: "Язык",
        EN: "Anglaise",
        FA: "Persane",
        FR: "Française",
        RU: "Pусский",
        WELCOME_STRING: "ٌДобро пожаловать в наше приложение для покупок",
        Enter_to_app: "Войти в приложение",
        UserName: "Электронная почта или номер телефона",
        Password: "пароль",
        ForgetPassword: "Забыли свой пароль?",
        Make_New_Account: "Создать новую учетную запись",
        Terms: "Входя в программу или регистрируясь в ней, вы принимаете условия использования сервисов приложения и его правила конфиденциальности",
        REGIONAL: "Региональный",
        DarkMode: "Темный режим",
    },
    fa: {
        Dir: "rtl",
        MY_APP: "برنامه من",
        SHOP: "سبد خرید",
        CATEGORIES: "دسته بندی ها",
        HOME: "خانه",
        SETTINGS: "تنظیمات",
        LANGUAGE: "زبان",
        EN: "انگلیسی",
        FA: "فارسی",
        FR: "فرانسوی",
        RU: "روسی",
        WELCOME_STRING: "به برنامه فروشگاهی ما خوش آمدید",
        Enter_to_app: "ورود به برنامه",
        UserName: "پست الکترونیک یا شماره موبایل",
        Password: "کلمه عبور خود را وارد نمایید",
        ForgetPassword: "رمز عبور خود را فراموش کرده اید؟",
        Make_New_Account: "ساخت حساب کاربری جدید",
        Terms: " با ورود و یا ثبت نام در برنامه شما شرایط و قوانین استفاده از سرویس های برنامه و قوانین حریم خصوصی آن را می پذیرید",
        REGIONAL: "منطقه ایی",
        DarkMode: "زمینه تاریک",
    },
    fr: {
        Dir: "ltr",
        MY_APP: "Mon appli",
        SHOP: "boutique",
        CATEGORIES: "Catégories",
        HOME: "Domicile",
        SETTINGS: "Réglages",
        LANGUAGE: "Langue",
        EN: "Anglaise",
        FA: "Persane",
        FR: "Française",
        RU: "russe",
        WELCOME_STRING: "ٌBienvenue sur notre application shopping",
        Enter_to_app: "Entrez dans l'application",
        UserName: "Email ou numéro de téléphone",
        Password: "mot de passe",
        ForgetPassword: "Mot de passe oublié?",
        Make_New_Account: "Créer un nouveau compte",
        Terms: "En entrant ou en vous inscrivant au programme, vous acceptez les termes et conditions d'utilisation des services de l'application et ses règles de confidentialité",
        REGIONAL: "Régionale",
        DarkMode: "Mode sombre",
    },
})

export default Strings;